# https://github.com/LlmKira/contributor/blob/main/.nerve.toml
contributor = "fae6f549-fcd5-4c57-89ab-04c97ebb11cb"
language = "English"
issue_auto_label = true
issue_title_format = true
issue_body_format = false
issue_close_with_report = true
