# https://github.com/LlmKira/contributor/blob/main/.nerve.toml
contributor = "9f30f440-3d09-43dd-aa61-285c66f89356"
language = "English"
issue_auto_label = true
issue_title_format = true
issue_body_format = false
issue_close_with_report = true
